[package]
name = "quadder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.12.0"
serde = {version = "1.0.142", features = ["derive"]}
serde_json = "1.0.83"
dirs = "4.0.0"